/**
* \file    ComTest1_DLL_Wrapper.h
* \brief	Warper for dLL file
* \details Wrapper for DLL.
* Only for testing purposes.
* \author  PB
* \date    2014/12/03
*/

#ifndef ComTest1_DLL_Warper_h__
#define ComTest1_DLL_Warper_h__

#include "definitions.h"
#include "extcode.h"
/* lv_prolog.h and lv_epilog.h set up the correct alignment for LabVIEW data. */
#include "lv_prolog.h"

/**
 * /struct TD1
 * /brief struct generated by LV after wiring the diagram.
 */
typedef struct {
	int32_t PictureFirstElementAddress;
	int32_t LineWidthPixels;
	int32_t PixelSizeBytes;
	int32_t PictureRows;
	int32_t PictureColumns;
} TD1;

#include "lv_epilog.h"
/// Exported method from DLL
extern "C" __declspec(dllexport) void saveImage(TD1* input);

#endif
